# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx format:check
      # - run: npx nx run-many --target=lint
      # - run: npx nx run-many --target=build
      # - run: npx nx run-many --target=test --configuration=ci
      - run: npx nx affected lint --parallel=3
      - run: npx nx affected test --parallel=3
      - run: npx nx affected build --parallel=3
