name: Release

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - name: Detect changed directories
        uses: gagle/nx-check-changes@v1.0.0
        id: nx-changes

      - name: Log affected directories
        run: echo "Changed directories: ${{ steps.nx-changes.outputs.changed-dirs }}"

      # - run: npx nx run-many --target=lint
      # - run: npx nx run-many --target=build
      # - run: npx nx run-many --target=test --configuration=ci
